blog/urls.py
from django.urls import path
from .views import index, IndexView
from .views import BlogListView, BlogCreateView, create_done, BlogDetailView, BlogEditView, edit_done
from .views import BlogDeleteView, delete_done, CategoryView, SearchPostView

app_name = 'blog'

urlpatterns = [
    path('index', index, name="index"),
    path('index_class', IndexView.as_view(), name="index_class"),
    path('', BlogListView.as_view(), name="blog_list"),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('create_done/', create_done, name='create_done'),
    path('detail/<int:pk>/', BlogDetailView.as_view(), name="detail"),
    path('edit/<int:pk>/', BlogEditView.as_view(), name='edit'),
    path('edit_done/', edit_done, name='edit_done'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
    path('delete_done/', delete_done, name='delete_done'),
    path('category/<str:category>/', CategoryView.as_view(), name='category'),
    path('search_list/', SearchPostView.as_view(), name='search_list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('management/', admin.site.urls),
    # path('blog/', include('blog.urls')),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    class Meta:
        db_table = "category"
        verbose_name = "カテゴリ名"
        verbose_name_plural = "カテゴリ名"

    category_name = models.CharField(
        verbose_name="カテゴリ名", max_length=100, unique=True)
    category_image = models.ImageField(
        verbose_name="カテゴリ画像", upload_to="images/")

    def __str__(self):
        return self.category_name


class Blog(models.Model):
    class Meta:
        db_table = "blog"
        verbose_name = "ブログ記事"
        verbose_name_plural = "ブログ記事"

    title = models.CharField(verbose_name="タイトル", max_length=100)
    content = models.TextField(verbose_name="内容")
    postdate = models.DateField(verbose_name="投稿日", auto_now_add=True)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, verbose_name="カテゴリ")

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
    """
    新規データ登録画面用のフォーム定義
    """
    class Meta:
        model = Blog
        fields =['title', 'content', 'category']

blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView  # 追加
from .models import Blog, Category
from . forms import BlogForm
from django.urls import reverse_lazy
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


def index(request):  # 関数ベース
    # TOP画面を表示する関数
    # return render(request, 'index.html')
    print("index関数を使ってTOP画面を表示します！関数ベース")
    return render(request, 'blog/index.html')


class IndexView(TemplateView):  # クラスベース
    # TOP画面を表示するクラス
    template_name = 'blog/index.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        print("IndexViewを使ってTOP画面を表示します！クラスベース")
        return self.render_to_response(context)


class BlogListView(ListView):
    template_name = 'blog/blog_list.html'
    model = Blog
    queryset = Blog.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BlogListView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class BlogCreateView(LoginRequiredMixin, CreateView):

    model = Blog
    form_class = BlogForm
    # 登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('blog:create_done')

    def get_context_data(self, **kwargs):
        context = super(BlogCreateView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


def create_done(request):
    # 登録処理が正常終了した場合に呼ばれるテンプレートを指定
    category_list = Category.objects.all()  # 追加
    return render(request, 'blog/create_done.html', {
        'category_list': category_list})  # category_listを追加


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog/blog_detail.html'

    def get_context_data(self, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class BlogEditView(LoginRequiredMixin, UpdateView):

    model = Blog
    form_class = BlogForm
    template_name = 'blog/blog_form.html'

    # 登録処理が正常終了した場合の遷移先を指定
    success_url = reverse_lazy('blog:edit_done')

    def get_context_data(self, **kwargs):
        context = super(BlogEditView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        context['message_type'] = "edit"
        return context


def edit_done(request):
    # 更新処理が正常終了した場合に呼ばれるテンプレートを指定
    category_list = Category.objects.all()
    return render(request, 'blog/edit_done.html', {
        'category_list': category_list})


class BlogDeleteView(LoginRequiredMixin, DeleteView):

    model = Blog
    template_name = 'blog/blog_confirm_delete.html'
    success_url = reverse_lazy('blog:delete_done')

    def get_context_data(self, **kwargs):
        context = super(BlogDeleteView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


def delete_done(request):
    category_list = Category.objects.all()
    return render(request, 'blog/delete_done.html', {
        'category_list': category_list})


class CategoryView(ListView):
    """カテゴリ名でフィルタ検索"""
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_queryset(self):
        """カテゴリでの絞り込み"""
        category_name = self.kwargs['category']
        queryset = Blog.objects.filter(category__category_name=category_name)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context


class SearchPostView(ListView):
    model = Blog
    template_name = 'blog/blog_list.html'

    def get_queryset(self):
        """
        request.GETには GET リクエストのパラメータが含まれています。
        request.GET.get('q', None)でqパラメータの値を取得し、値が
        存在しない場合はNoneを取得します。
        """
        query = self.request.GET.get('q', None)

        if query is not None:
            qs = Blog.objects.filter(Q(title__icontains=query) |
                                     Q(category__category_name__icontains=query))
            return qs

        else:
            qs = Blog.objects.all()
            return qs

    def get_context_data(self, *args, **kwargs):
        """クリックされたカテゴリを保持"""
        # context = super().get_context_data(*args, **kwargs)
        context = super(SearchPostView, self).get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        return context

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <title>Djangoブログサイト</title>
    <link rel="stylesheet" href="https://github.com/nicolas-cusan/destyle.css" />
    <link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  </head>

  <body id="portfolio">
    <!-- header始まり -->
    <header>
      <nav>
        <ul class="global-nav">
          <header>
            <nav>
              <ul class="global-nav">
                <li>
                  <a href="{% url 'blog:blog_list' %}">記事一覧</a>
                </li>
                {% if request.user.is_authenticated %}
                  <li>
                    <a href="{% url 'blog:create' %}">新規作成</a>
                  </li>
                  <li>
                    <a class="nav-link">ユーザ名：{{ request.user.get_username }}</a>
                  </li>
                  <li>
                    <a class="nav-link" href="{% url 'account_logout' %}"><i class="fa fa-fw fa-sign-out"></i>ログアウト</a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          </header>
        </ul>
      </nav>
    </header>
    <!-- header終わり -->

    {% block contents %}
      <!-- ここに個別のテンプレートの内容が組み込まれる -->
    {% endblock %}

    <!-- footer始まり -->
    <footer>
      <small>(C)2022 django-blog</small>
    </footer>
    <!-- footer終わり -->
  </body>
</html>

templates/blog/blog_confirm_delete.html
{% extends './base.html' %}

{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
          <p>タイトル【<span class=delete-title>{{ object }}</span>】 のデータを削除していいですか?</p>
          <form method="post">
            <button class="button">削除</button>
          
            {% csrf_token %}
          </form>
      </section>
 <!-- ここまで記事の登録-->

 <table>
  <tr>
  <td><p class="btn"><a href="{% url 'blog:blog_list' %}">戻る</a></td>
    </tr>
  </table>  
     </div> <!-- end main -->
     <!-- カテゴリ一覧の表示 start -->
     {% include 'blog/widgets/side_category.html' %}
    　<!-- カテゴリ一覧の表示 end -->
    </div> <!-- end content-->
  </div>   <!-- end wrap -->
  {% endblock %}

templates/blog/blog_detail.html
{% extends './base.html' %}

{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
        <h1>記事の詳細画面</h1>
        <table>
          <tr>
            <th>タイトル</th>
            <td>{{ object.title }}
            </td>
          </tr>
          <tr>
            <th>カテゴリ</th>
            <td> {{ object.category }}</td>
          </tr>
          <tr>
            <th>内容</th>
            <td>{{ object.content|linebreaksbr }}
            </td>
          </tr>
          <tr>
            <th>作成日時</th>
            <td>{{ object.postdate }}
            </td>
          </tr>  
        </table>
      </section>
      <table>
        <tr>
          <td><p class="btn"><a href="{% url 'blog:blog_list' %}">戻る</a></td>
          {% if request.user.is_authenticated %}
          <td><p class="btn-edit"><a href="{% url 'blog:edit' object.pk %}">編集</a></td>
          <td><p class="btn-delete"><a href="{% url 'blog:delete' object.pk %}">削除</a></td>
          {% endif %}
        </tr>
      </table>  
 <!-- ここまで記事の詳細-->
     </div> <!-- end main -->
     <!-- カテゴリ一覧の表示 start -->
     {% include 'blog/widgets/side_category.html' %}
    　<!-- カテゴリ一覧の表示 end -->
    </div> <!-- end content-->
  </div>   <!-- end wrap -->
  {% endblock %}

templates/blog/blog_form.html
{% extends './base.html' %}

{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
        <h1>記事の新規登録</h1>
        <form method="POST">
              {{ form }}
          {% csrf_token %}
          
          <button class="button" type="submit">登録</button>
 
      </form>
      </section>
 <!-- ここまで記事の登録-->

 <table>
  <tr>
  <td><p class="btn"><a href="{% url 'blog:blog_list' %}">戻る</a></td>
    </tr>
  </table>  
     </div> <!-- end main -->
     <!-- カテゴリ一覧の表示 start -->
     {% include 'blog/widgets/side_category.html' %}
    　<!-- カテゴリ一覧の表示 end -->
    </div> <!-- end content-->
  </div>   <!-- end wrap -->
{% endblock %}

templates/blog/blog_list.html
{% extends './base.html' %}
{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <h1>記事一覧</h1>

        <form class="form-inline my-2 my-lg-0" action="{% url 'blog:search_list' %}" method="GET">
          <!-- 送信先に渡すnameとvalueを指定 -->
          <input class="form-control mr-sm-2" type="search" name="q" value="{{ request.GET.q }}" placeholder="Search" aria-label="Search" />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
        </form>

        <!-- ここから記事一覧 -->
        {% for item in object_list %}
          <section>
            <h1>{{ item.title }}</h1>
            <ul>
              <li>
                <a><img src="http://127.0.0.1:8000/media/{{ item.category.category_image }}" /></a>
                <div class="title">
                  <b>{{ item.category }}</b>
                </div>
              </li>
              <p>
                {{ item.content|linebreaksbr|truncatechars:100 }}<a href="{% url 'blog:detail' item.pk %}">詳しくみる ≫</a>
              </p>
            </ul>
          </section>
        {% endfor %}
        <!-- ここまで記事一覧 -->
      </div> <!-- end main -->
      {% include 'blog/widgets/side_category.html' %}
    </div> <!-- end content -->
  </div> <!-- end wrap -->
{% endblock %}

templates/blog/create_done.html
{% extends './base.html' %}

{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
        <h1>登録完了</h1>
        <div>記事の新規登録が完了しました。</div>
      </section>

 <table>
  <tr>
  <td><p class="btn"><a href="{% url 'blog:blog_list' %}">戻る</a></td>
    </tr>
  </table>  
     </div> <!-- end main -->
     <!-- カテゴリ一覧の表示 start -->
     {% include 'blog/widgets/side_category.html' %}
    　<!-- カテゴリ一覧の表示 end -->
    </div> <!-- end content-->
  </div>   <!-- end wrap -->
{% endblock %}

templates/blog/delete_done.html
{% extends './base.html' %}

{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
        <h1>削除完了</h1>
        <div>記事削除が完了しました。</div>
      </section>
 <!-- ここまで記事の登録-->

 <table>
  <tr>
  <td><p class="btn"><a href="{% url 'blog:blog_list' %}">戻る</a></td>
    </tr>
  </table>  
     </div> <!-- end main -->
     <!-- カテゴリ一覧の表示 start -->
     {% include 'blog/widgets/side_category.html' %}
    　<!-- カテゴリ一覧の表示 end -->
    </div> <!-- end content-->
  </div>   <!-- end wrap -->
  {% endblock %}

templates/blog/edit_done.html
{% extends './base.html' %}

{% block contents %}
  <!-- wrap始まり -->
  <div id="wrap" class="clearfix">
    <div class="content">
      <div class="main">
        <section class="career">
        <h1>更新完了</h1>
        <div>記事の更新が完了しました。</div>
      </section>
 <!-- ここまで記事の登録-->

 <table>
  <tr>
  <td><p class="btn"><a href="{% url 'blog:blog_list' %}">戻る</a></td>
    </tr>
  </table>  
     </div> <!-- end main -->
     <!-- カテゴリ一覧の表示 start -->
     {% include 'blog/widgets/side_category.html' %}
    　<!-- カテゴリ一覧の表示 end -->
    </div> <!-- end content-->
  </div>   <!-- end wrap -->
  {% endblock %}

templates/blog/index.html
これはTOP画面です！

templates/blog/widgets/side_category.html
<aside class="sidebar">
  <h2>Category</h2>
  <ul>
    {% for category in category_list %}
      <li><a href="{% url 'blog:category' category.category_name %}">{{category.category_name}}</a></li
    {% endfor %}
  </ul>
</aside>